builds:
- env:
  - CGO_ENABLED=0
  goos: 
    - linux
    - darwin
    - windows
  ldflags:
    - -s -w -X github.com/similarweb/kubectl-ipick/cmd.Version="{{.Version}}" -X github.com/similarweb/kubectl-ipick/cmd.Commit={{.Commit}} -X github.com/similarweb/kubectl-ipick/cmd.date={{.Date}} -X github.com/similarweb/kubectl-ipick/cmd.builtBy=goreleaser
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: 386
    - goos: linux
      goarch: 386
    - goos: linux
      goarch: arm
      goarm: 7
archives:
  - id: kubectl-ipick
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
