apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ipick
spec:
  version: {{ .TagName }}
  homepage: https://github.com/similarweb/kubectl-ipick
  shortDescription: A kubectl wrapper for interactive resource selection.
  description: |
    This plugin is a smart wrapper around kubectl, which lets you pick 
    the resource to act on. For example, `kubectl ipick exec` will
    show a list of pods and execute `kubectl exec <selected-pod>`.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/similarweb/kubectl-ipick/releases/download/{{ .TagName }}/kubectl-ipick_{{ .TagName }}_Darwin_x86_64.tar.gz" .TagName }}
    bin: kubectl-ipick
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/similarweb/kubectl-ipick/releases/download/{{ .TagName }}/kubectl-ipick_{{ .TagName }}_Linux_x86_64.tar.gz" .TagName }}
    bin: kubectl-ipick
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/similarweb/kubectl-ipick/releases/download/{{ .TagName }}/kubectl-ipick_{{ .TagName }}_Windows_x86_64.tar.gz" .TagName }}    
    bin: kubectl-ipick.exe